# This is a basic workflow that is manually triggered

name: End to end test (Selenium)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout this repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install software
      run: sudo apt install -y chromium-browser
    - name: Install software
      run: pip install -r ./testrequirements.txt
    - name: Run  the test
      run: python ./test_fullTest.py
